export const c = {
  id: 'c',
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  topLine: '',
  headline: 'Learn C/C++',
  description: 'C and C++ are considered "low-level" languages, meaning they provide a close-to-hardware level of control. Learning these languages can help you understand the fundamental concepts of programming, memory management, and system architecture',
  description1:'Knowing C/C++ can provide a solid foundation for understanding higher-level languages like Java, C#, or Python. Learning lower-level languages can give you insights into how higher-level abstractions are implemented.',
  description2:"Many job positions in the software industry require or prefer knowledge of C/C++. If you're looking to pursue a career in fields like systems programming, game development, or performance optimization, learning C/C++ can enhance your job prospects.",
  buttonLabel: 'Enquire Now',
  imgStart: false,
  img: '/images/c.png',
  alt: 'Image',
  dark: true,
  primary: true,
  darkText: false
};
export const java = {
  id: 'java',
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  topLine: '',
  headline: 'Learn java',
  description: 'Java is designed to be platform-independent, meaning that Java programs can run on any device that has a Java Virtual Machine (JVM). This "write once, run anywhere" feature makes Java suitable for developing cross-platform applications.',
  description1: 'Java is a versatile language used for various types of applications, including web development, mobile applications (Android development), enterprise applications, scientific applications, and more.',
  description2: 'Java is an object-oriented programming language, which encourages modular and reusable code. Learning Java will help you understand key OOP concepts such as encapsulation, inheritance, and polymorphis.',
  buttonLabel: 'Enquire Now',
  imgStart: false,
  img: '/images/java.png',
  alt: 'Image',
  dark: true,
  primary: true,
  darkText: false
};export const python = {
  id: 'python',
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  topLine: '',
  headline: 'Learn Python',
  description: 'Python is known for its readability and simplicity. It has a clean and easy-to-understand syntax, making it an ideal language for beginners.',
  description1: 'Python is a versatile language used in various domains, including web development, data science, artificial intelligence, machine learning, automation, scientific computing, and more. It can be applied to different types of projects and industries.',
  description2: 'Python has a large and active community of developers. This means ample resources such as documentation, tutorials, forums, and libraries are available, making it easier to find help and solutions to problems.',
  buttonLabel: 'Enquire Now',
  imgStart: false,
  img: '/images/python.png',
  alt: 'Image',
  dark: true,
  primary: true,
  darkText: false
};export const ml = {
  id: 'ml',
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  topLine: '',
  headline: 'Learn Machine learning',
  description: 'ML is a rapidly growing field with high demand for skilled professionals. Learning ML can open up various career paths, including data science, artificial intelligence, and machine learning engineering.',
  description1:'ML enables you to develop systems that can learn from data and make predictions or decisions. This can lead to innovative solutions to complex problems in various domains, such as healthcare, finance, and technology.',
  description2:"Job Opportunities: ML can empower you to create innovative products and solutions. Many successful startups leverage ML to develop cutting-edge technologies and disrupt traditional industries.",
  buttonLabel: 'Enquire Now',
  imgStart: false,
  img: '/images/machine-learning.png',
  alt: 'Image',
  dark: true,
  primary: true,
  darkText: false
};export const ai = {
  id: 'ai',
  lightBg: false,
  lightText: true,
  lighttextDesc: true,
  topLine: '',
  headline: 'Learn Artificial inteligence',
  description: ' AI is a rapidly growing field with increasing demand for skilled professionals. Learning AI can open up various job opportunities in industries such as healthcare, finance, manufacturing, and technology.',
  description1: 'AI is at the forefront of technological innovation. By understanding AI concepts and techniques, you can contribute to creating cutting-edge solutions and advancements in various domains.',
  description2: 'AI can automate repetitive and mundane tasks, allowing individuals and organizations to focus on more creative and strategic activities. Learning AI can help you leverage automation to increase efficiency.',
  buttonLabel: 'Enquire Now',
  imgStart: false,
  img: '/images/technology.png',
  alt: 'Image',
  dark: true,
  primary: true,
  darkText: false
};